name: Generate PDF from LaTeX

permissions:
    contents: write

on:
    push:
        paths:
            - "src/**/*.tex"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Compile LaTeX Resume
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: src/resume.tex

            - name: Move PDF to bin
              run: mv -f resume.pdf bin/resume.pdf

            - name: Upload PDF Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: resume
                  path: bin/resume.pdf

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: bin/resume.pdf

            - name: Commit PDF
              run: |
                  git config --local user.email ""
                  git config --local user.name "GitHub Action"
                  git add bin/resume.pdf
                  git commit -m "chore: auto generate resume.pdf"
                  git push
